[package]
name = "lighthouse-automation"
version = "0.1.0"
edition = "2021"

[dependencies]
enigo = "0.2.1"
fantoccini = "0.21.0"
geckodriver = "0.34.0"
tokio = { version = "1.38.1", features = ["full"] }
